INSERT INTO `airlines` (`id`, `name`, `airline_iata`, `created_at`, `updated_at`) VALUES
(1, 'ABSA Cargo Airline', 'M3', NULL, NULL),
(2, 'ABX Air', 'GB', NULL, NULL),
(3, 'ACT Airlines', '9T', NULL, NULL),
(4, 'ANA & JP Express', '9N', NULL, NULL),
(5, 'ATRAN Cargo Airlines', 'V8', NULL, NULL),
(6, 'AVE.com', '2E', NULL, NULL),
(7, 'Aban Air', 'K5', NULL, NULL),
(8, 'Abelag Aviation', 'W9', NULL, NULL),
(9, 'Abu Dhabi Amiri Flight', 'MO', NULL, NULL),
(10, 'Ada Air', 'ZY', NULL, NULL),
(11, 'Adria Airways', 'JP', NULL, NULL),
(12, 'Aegean Airlines', 'A3', NULL, NULL),
(13, 'Aer Arann', 'RE', NULL, NULL),
(14, 'Aer Lingus', 'EI', NULL, NULL),
(15, 'Aero Asia International', 'E4', NULL, NULL),
(16, 'Aero Benin', 'EM', NULL, NULL),
(17, 'Aero Caribbean', '7L', NULL, NULL),
(18, 'Aero Condor Peru', 'Q6', NULL, NULL),
(19, 'Aero Contractors', 'AJ', NULL, NULL),
(20, 'Aero Lanka', 'QL', NULL, NULL),
(21, 'Aero Mongolia', 'M0', NULL, NULL),
(22, 'Aero Services Executive', 'W4', NULL, NULL),
(23, 'Aero-Charter Ukraine', 'DW', NULL, NULL),
(24, 'Aero-Service', 'BF', NULL, NULL),
(25, 'Aero-Tropics Air Services', 'HC', NULL, NULL),
(26, 'AeroLogic', '3S', NULL, NULL),
(27, 'Aeroméxico', 'AM', NULL, NULL),
(28, 'AeroRepublica', 'P5', NULL, NULL),
(29, 'AeroSucre', '6N', NULL, NULL),
(30, 'Aerocondor', '2B', NULL, NULL),
(31, 'Aeroflot Russian Airlines', 'SU', NULL, NULL),
(32, 'Aeroflot-Cargo', 'SU', NULL, NULL),
(33, 'Aeroflot-Don', 'D9', NULL, NULL),
(34, 'Aeroflot-Nord', '5N', NULL, NULL),
(35, 'Aerogaviota', 'KG', NULL, NULL),
(36, 'Aerolineas Argentinas', 'AR', NULL, NULL),
(37, 'Aerolineas Galapagos (Aerogal)', '2K', NULL, NULL),
(38, 'Aerolineas Sosa', 'P4', NULL, NULL),
(39, 'Aeromar', 'VW', NULL, NULL),
(40, 'Aeromexpress', 'QO', NULL, NULL),
(41, 'Aeromist-Kharkiv', 'HT', NULL, NULL),
(42, 'Aeroméxico Connect', '5D', NULL, NULL),
(43, 'Aeropelican Air Services', 'OT', NULL, NULL),
(44, 'Aeroperlas', 'WL', NULL, NULL),
(45, 'Aeropostal Alas de Venezuela', 'VH', NULL, NULL),
(46, 'Aerosur', '5L', NULL, NULL),
(47, 'Aerosvit Airlines', 'VV', NULL, NULL),
(48, 'Africa West', 'FK', NULL, NULL),
(49, 'African Express Airways', 'XU', NULL, NULL),
(50, 'Afrijet Airlines', '6F', NULL, NULL),
(51, 'Afrinat International Airlines', 'Q9', NULL, NULL),
(52, 'Afriqiyah Airways', '8U', NULL, NULL),
(53, 'Aigle Azur', 'ZI', NULL, NULL),
(54, 'Air Algerie', 'AH', NULL, NULL),
(55, 'Air Alpha Greenland', 'GD', NULL, NULL),
(56, 'Air Alps Aviation', 'A6', NULL, NULL),
(57, 'Air Arabia', 'G9', NULL, NULL),
(58, 'Air Armenia', 'QN', NULL, NULL),
(59, 'Air Astana', 'KC', NULL, NULL),
(60, 'Air Atlanta Icelandic', 'CC', NULL, NULL),
(61, 'Air Atlantique', 'KI', NULL, NULL),
(62, 'Air Austral', 'UU', NULL, NULL),
(63, 'Air Bagan', 'W9', NULL, NULL),
(64, 'Air Baltic', 'BT', NULL, NULL),
(65, 'Air Berlin', 'AB', NULL, NULL),
(66, 'Air Botswana', 'BP', NULL, NULL),
(67, 'Air Burkina', '2J', NULL, NULL),
(68, 'Air Caledonie', 'TY', NULL, NULL),
(69, 'Air Canada', 'AC', NULL, NULL),
(70, 'Air Canada Jazz', 'QK', NULL, NULL),
(71, 'Air Caraibes', 'TX', NULL, NULL),
(72, 'Air Cargo Carriers', '2Q', NULL, NULL),
(73, 'Air Central', 'NV', NULL, NULL),
(74, 'Air Chathams', 'CV', NULL, NULL),
(75, 'Air China', 'CA', NULL, NULL),
(76, 'Air China Cargo', 'CA', NULL, NULL),
(77, 'Air Class Lineas Aereas', 'QD', NULL, NULL),
(78, 'Air Comet', 'A7', NULL, NULL),
(79, 'Air Contractors', 'AG', NULL, NULL),
(80, 'Air Corridor', 'QC', NULL, NULL),
(81, 'Air Creebec', 'YN', NULL, NULL),
(82, 'Air Dolomiti', 'EN', NULL, NULL),
(83, 'Air Europa', 'UX', NULL, NULL),
(84, 'Air Fiji', 'PC', NULL, NULL),
(85, 'Air Finland', 'OF', NULL, NULL),
(86, 'Air France', 'AF', NULL, NULL),
(87, 'Air Freight NZ', 'AF', NULL, NULL),
(88, 'Air Georgian', 'ZX', NULL, NULL),
(89, 'Air Glaciers', '7T', NULL, NULL),
(90, 'Air Greenland', 'GL', NULL, NULL),
(91, 'Air Guinea Cargo', 'LQ', NULL, NULL),
(92, 'Air Guyane Express', 'GG', NULL, NULL),
(93, 'Air Hong Kong', 'LD', NULL, NULL),
(94, 'Air Horizon', '8C', NULL, NULL),
(95, 'Air Iceland Connect', 'NY', NULL, NULL),
(96, 'Air India', 'AI', NULL, NULL),
(97, 'Air India Express', 'IX', NULL, NULL),
(98, 'Air India Regional', 'CD', NULL, NULL),
(99, 'Air Inuit', '3H', NULL, NULL),
(100, 'Air Italy', 'I9', NULL, NULL),
(101, 'Air Italy Polska', '4Q', NULL, NULL),
(102, 'Air Ivoire', 'VU', NULL, NULL),
(103, 'Air Jamaica', 'JM', NULL, NULL),
(104, 'Air Japan', 'NQ', NULL, NULL),
(105, 'Air Kiribati', '4A', NULL, NULL),
(106, 'Air Kokshetau', '0K', NULL, NULL),
(107, 'Air Koryo', 'JS', NULL, NULL),
(108, 'Air Labrador', 'WJ', NULL, NULL),
(109, 'Air Libya', '7Q', NULL, NULL),
(110, 'Air Macao', 'NX', NULL, NULL),
(111, 'Air Madagascar', 'MD', NULL, NULL),
(112, 'Air Malawi', 'QM', NULL, NULL),
(113, 'Air Mali International', 'XG', NULL, NULL),
(114, 'Air Malta', 'KM', NULL, NULL),
(115, 'Air Marshall Islands', 'CW', NULL, NULL),
(116, 'Air Mauritius', 'MK', NULL, NULL),
(117, 'Air Mediterranee', 'DR', NULL, NULL),
(118, 'Air Mobility Command', 'MC', NULL, NULL),
(119, 'Air Moldova', '9U', NULL, NULL),
(120, 'Air Namibia', 'SW', NULL, NULL),
(121, 'Air Nelson', 'NZ', NULL, NULL),
(122, 'Air New Zealand', 'NZ', NULL, NULL),
(123, 'Air Next', '7A', NULL, NULL),
(124, 'Air Nippon', 'EL', NULL, NULL),
(125, 'Air Nippon Network Co. Ltd.', 'EH', NULL, NULL),
(126, 'Air Niugini', 'PX', NULL, NULL),
(127, 'Air North', '4N', NULL, NULL),
(128, 'Air Norway', 'M3', NULL, NULL),
(129, 'Air Nostrum', 'YW', NULL, NULL),
(130, 'Air One', 'AP', NULL, NULL),
(131, 'Air Pacific', 'FJ', NULL, NULL),
(132, 'Air People International', '3D', NULL, NULL),
(133, 'Air Philippines', '2P', NULL, NULL),
(134, 'Air Pullmantur', 'EB', NULL, NULL),
(135, 'Air Saint Pierre', 'PJ', NULL, NULL),
(136, 'Air Satellite', '6O', NULL, NULL),
(137, 'Air Senegal International', 'V7', NULL, NULL),
(138, 'Air Service Gabon', 'G8', NULL, NULL),
(139, 'Air Seychelles', 'HM', NULL, NULL),
(140, 'Air Sinai', '4D', NULL, NULL),
(141, 'Air Slovakia', 'GM', NULL, NULL),
(142, 'Air Southwest', 'WO', NULL, NULL),
(143, 'Air Sunshine', 'YI', NULL, NULL),
(144, 'Air Tahiti', 'VT', NULL, NULL),
(145, 'Air Tahiti Nui', 'TN', NULL, NULL),
(146, 'Air Transat', 'TS', NULL, NULL),
(147, 'Air Transport International LLC', '8C', NULL, NULL),
(148, 'Air Turks and Caicos', 'JY', NULL, NULL),
(149, 'Air Uganda', 'U7', NULL, NULL),
(150, 'Air Urga', '3N', NULL, NULL),
(151, 'Air VIA', 'VL', NULL, NULL),
(152, 'Air Vall', 'DO', NULL, NULL),
(153, 'Air Vanuatu', 'NF', NULL, NULL),
(154, 'Air Wisconsin', 'ZW', NULL, NULL),
(155, 'Air Zambezi', 'ZT', NULL, NULL),
(156, 'Air Zimbabwe', 'UM', NULL, NULL),
(157, 'Air2there', 'F8', NULL, NULL),
(158, 'AirAsia', 'AK', NULL, NULL),
(159, 'AirAsia X', 'D7', NULL, NULL),
(160, 'AirBridgeCargo Airlines', 'RU', NULL, NULL),
(161, 'AirTran Airways', 'FL', NULL, NULL),
(162, 'Airbus Industrie', 'AP', NULL, NULL),
(163, 'Aircalin (Air Caledonie International)', 'SB', NULL, NULL),
(164, 'Aires, Aerovias de Integracion Regional, S.A.', '4C', NULL, NULL),
(165, 'Airkenya Express', 'P2', NULL, NULL),
(166, 'Airlinair', 'A5', NULL, NULL),
(167, 'Airlines Of Tasmania', 'FO', NULL, NULL),
(168, 'Airlines PNG', 'CG', NULL, NULL),
(169, 'Airlink', '4Z', NULL, NULL),
(170, 'Airnorth', 'TL', NULL, NULL),
(171, 'Airstars', 'PL', NULL, NULL),
(172, 'Aklak Air', '6L', NULL, NULL),
(173, 'Alania Airlines', '2D', NULL, NULL),
(174, 'Alaska Airlines', 'AS', NULL, NULL),
(175, 'Alaska Central Express', 'KO', NULL, NULL),
(176, 'Albanian Airlines', 'LV', NULL, NULL),
(177, 'Alidaunia', 'D4', NULL, NULL),
(178, 'Alitalia', 'AZ', NULL, NULL),
(179, 'Alitalia Express', 'XM', NULL, NULL),
(180, 'All Nippon Airways', 'NH', NULL, NULL),
(181, 'Allegiant Air', 'G4', NULL, NULL),
(182, 'Allegro', 'LL', NULL, NULL),
(183, 'Alliance Airlines', 'QQ', NULL, NULL),
(184, 'Almaty Aviation', '6T', NULL, NULL),
(185, 'Aloha Air Cargo', 'KH', NULL, NULL),
(186, 'Alpine Air Express', '5A', NULL, NULL),
(187, 'Alrosa Mirny Air Enterprise', '6R', NULL, NULL),
(188, 'Amaszonas', 'Z8', NULL, NULL),
(189, 'American Airlines', 'AA', NULL, NULL),
(190, 'American Eagle Airlines', 'MQ', NULL, NULL),
(191, 'Ameriflight', 'A8', NULL, NULL),
(192, 'Amerijet International', 'M6', NULL, NULL),
(193, 'Amsterdam Airlines', 'WD', NULL, NULL),
(194, 'Andes Líneas Aéreas', 'OY', NULL, NULL),
(195, 'Angel Airlines', '8G', NULL, NULL),
(196, 'Antrak Air', '4', NULL, NULL),
(197, 'Arctic Circle Air Service', '5F', NULL, NULL),
(198, 'Arcus-Air Logistic', 'ZE', NULL, NULL),
(199, 'Ariana Afghan Airlines', 'FG', NULL, NULL),
(200, 'Arik Air', 'W3', NULL, NULL),
(201, 'Arkefly', 'OR', NULL, NULL),
(202, 'Arkia Israel Airlines', 'IZ', NULL, NULL),
(203, 'Armavia', 'U8', NULL, NULL),
(204, 'Arrow Air', 'JW', NULL, NULL),
(205, 'Aserca Airlines', 'R7', NULL, NULL),
(206, 'Asian Express Airlines', 'HJ', NULL, NULL),
(207, 'Asiana Airlines', 'OZ', NULL, NULL),
(208, 'Askari Aviation', '4K', NULL, NULL),
(209, 'Astar Air Cargo', 'ER', NULL, NULL),
(210, 'Astraeus', '5W', NULL, NULL),
(211, 'Astrakhan Airlines', 'OB', NULL, NULL),
(212, 'Astral Aviation', '8V', NULL, NULL),
(213, 'Atlant-Soyuz Airlines', '3G', NULL, NULL),
(214, 'Atlantic Airlines de Honduras', 'ZF', NULL, NULL),
(215, 'Atlantic Airways', 'RC', NULL, NULL),
(216, 'Atlantic Southeast Airlines', 'EV', NULL, NULL),
(217, 'Atlantis European Airways', 'TD', NULL, NULL),
(218, 'Atlas Air', '5Y', NULL, NULL),
(219, 'Atlas Blue', '8A', NULL, NULL),
(220, 'Atlasjet', 'KK', NULL, NULL),
(221, 'Atyrau Air Ways', 'IP', NULL, NULL),
(222, 'Augsburg Airways GmbH', 'IQ', NULL, NULL),
(223, 'Aurigny Air Services', 'GR', NULL, NULL),
(224, 'Austral Lineas Aereas', 'AU', NULL, NULL),
(225, 'Australian air Express', 'XM', NULL, NULL),
(226, 'Austrian Airlines', 'OS', NULL, NULL),
(227, 'Austrian Arrows (Tyrolean Airways)', 'VO', NULL, NULL),
(228, 'Avia Traffic Company', 'TF', NULL, NULL),
(229, 'Aviacon Zitotrans', 'ZR', NULL, NULL),
(230, 'Aviacsa', '6A', NULL, NULL),
(231, 'Aviaenergo', '7U', NULL, NULL),
(232, 'Avialeasing Aviation Company', 'EC', NULL, NULL),
(233, 'Avianca - Aerovias Nacionales de Colombia, S.A.', 'AV', NULL, NULL),
(234, 'Aviastar-TU', '4B', NULL, NULL),
(235, 'Avient Aviation', 'Z3', NULL, NULL),
(236, 'Avies', 'U3', NULL, NULL),
(237, 'Aviogenex', 'JJ', NULL, NULL),
(238, 'Avior Airlines', '9V', NULL, NULL),
(239, 'Avirex', 'G2', NULL, NULL),
(240, 'Avitrans', '2Q', NULL, NULL),
(241, 'Axis Airways', '6V', NULL, NULL),
(242, 'Ayit Aviation and Tourism', '0', NULL, NULL),
(243, 'Azerbaijan Airlines', 'J2', NULL, NULL),
(244, 'Azul Brazilian Airlines', 'AD', NULL, NULL),
(245, 'B&H Airlines', 'JA', NULL, NULL),
(246, 'BA CityFlyer', 'CJ', NULL, NULL),
(247, 'BACH Flugbetriebsgesellschaft mbH', 'B4', NULL, NULL),
(248, 'BH Air (Balkan Holidays)', '1B', NULL, NULL),
(249, 'BMI Regional', 'BD', NULL, NULL),
(250, 'Bahamasair', 'UP', NULL, NULL),
(251, 'Bahrain Air', '2B', NULL, NULL),
(252, 'Bangkok Airways', 'PG', NULL, NULL),
(253, 'Bankair', 'B4', NULL, NULL),
(254, 'Barents AirLink', '8N', NULL, NULL),
(255, 'Batavia Air', '7P', NULL, NULL),
(256, 'Bearskin Lake Air Service', 'JV', NULL, NULL),
(257, 'Belair Airlines', '4T', NULL, NULL),
(258, 'Belavia Belarusian Airlines', 'B2', NULL, NULL),
(259, 'Belle Air', 'LZ', NULL, NULL),
(260, 'Bellview Airlines', 'B3', NULL, NULL),
(261, 'Bemidji Airlines', 'CH', NULL, NULL),
(262, 'Benin Golf Air', 'A8', NULL, NULL),
(263, 'Bering Air', '8E', NULL, NULL),
(264, 'Berjaya Air', 'J8', NULL, NULL),
(265, 'Best Air', '5Q', NULL, NULL),
(266, 'Bestair', 'T1', NULL, NULL),
(267, 'Biman Bangladesh Airlines', 'BG', NULL, NULL),
(268, 'Binter Canarias', 'NT', NULL, NULL),
(269, 'Bismillah Airlines', '5Z', NULL, NULL),
(270, 'Blue Air', '0B', NULL, NULL),
(271, 'Blue Dart Aviation', 'BZ', NULL, NULL),
(272, 'Blue Islands', 'SI', NULL, NULL),
(273, 'Blue Line', '4Y', NULL, NULL),
(274, 'Blue Panorama Airlines', 'BV', NULL, NULL),
(275, 'Blue Wings', 'QW', NULL, NULL),
(276, 'Blue1', 'KF', NULL, NULL),
(277, 'Bluebird Cargo', 'BF', NULL, NULL),
(278, 'Botir-Avia', 'B8', NULL, NULL),
(279, 'Bravo Air Congo', 'K6', NULL, NULL),
(280, 'Brindabella Airlines', 'FQ', NULL, NULL),
(281, 'Brit Air', 'DB', NULL, NULL),
(282, 'British Airways', 'BA', NULL, NULL),
(283, 'British International Helicopters', 'BS', NULL, NULL),
(284, 'Brussels Airlines', 'SN', NULL, NULL),
(285, 'Buffalo Airways', 'J4', NULL, NULL),
(286, 'Bulgaria Air', 'FB', NULL, NULL),
(287, 'Bulgarian Air Charter', '1T', NULL, NULL),
(288, 'Buraq Air', 'UZ', NULL, NULL),
(289, 'Business Aviation', '4P', NULL, NULL),
(290, 'CAL Cargo Air Lines', '5C', NULL, NULL),
(291, 'CCM Airlines', 'XK', NULL, NULL),
(292, 'CHC Airways', 'AW', NULL, NULL),
(293, 'CHC Helikopter Service', 'L5', NULL, NULL),
(294, 'Calm Air', 'MO', NULL, NULL),
(295, 'CanJet', 'C6', NULL, NULL),
(296, 'Canadian North', '5T', NULL, NULL),
(297, 'Cape Air', '9K', NULL, NULL),
(298, 'Capital Cargo International Airlines', 'PT', NULL, NULL),
(299, 'Cargo B Airlines', 'BB', NULL, NULL),
(300, 'Cargo Plus Aviation', '8L', NULL, NULL),
(301, 'Cargoitalia', '2G', NULL, NULL),
(302, 'Cargojet Airways', 'W8', NULL, NULL),
(303, 'Cargolux', 'CV', NULL, NULL),
(304, 'Caribair', 'B9', NULL, NULL),
(305, 'Caribbean Airlines', 'BW', NULL, NULL),
(306, 'Carpatair', 'V3', NULL, NULL),
(307, 'Caspian Airlines', 'RV', NULL, NULL),
(308, 'Cathay Pacific', 'CX', NULL, NULL),
(309, 'Cayman Airways', 'KX', NULL, NULL),
(310, 'Cebu Pacific', '5J', NULL, NULL),
(311, 'Central Mountain Air', '9M', NULL, NULL),
(312, 'Centralwings', 'C0', NULL, NULL),
(313, 'Centre-Avia', 'J7', NULL, NULL),
(314, 'Centurion Air Cargo', 'WE', NULL, NULL),
(315, 'Chanchangi Airlines', '3U', NULL, NULL),
(316, 'Chang\'an Airlines', '2Z', NULL, NULL),
(317, 'Chautauqua Airlines', 'RP', NULL, NULL),
(318, 'China Airlines', 'CI', NULL, NULL),
(319, 'China Cargo Airlines', 'CK', NULL, NULL),
(320, 'China Eastern Airlines', 'MU', NULL, NULL),
(321, 'China Postal Airlines', '8Y', NULL, NULL),
(322, 'China Southern Airlines', 'CZ', NULL, NULL),
(323, 'China United Airlines', 'HR', NULL, NULL),
(324, 'China West Air', 'PN', NULL, NULL),
(325, 'China Xinhua Airlines', 'XO', NULL, NULL),
(326, 'Chongqing Airlines', 'OQ', NULL, NULL),
(327, 'Cielos Airlines', 'A2', NULL, NULL),
(328, 'Cimber Air', 'QI', NULL, NULL),
(329, 'Cirrus Airlines', 'C9', NULL, NULL),
(330, 'City Airline', 'CF', NULL, NULL),
(331, 'City Connexion Airlines', 'G3', NULL, NULL),
(332, 'CityJet', 'WX', NULL, NULL),
(333, 'Click Airways', '4C', NULL, NULL),
(334, 'Clickair', 'XG', NULL, NULL),
(335, 'Colgan Air', '9L', NULL, NULL),
(336, 'Comair', 'MN', NULL, NULL),
(337, 'Comair', 'OH', NULL, NULL),
(338, 'CommutAir', 'C5', NULL, NULL),
(339, 'Comores Aviation', 'KR', NULL, NULL),
(340, 'Compagnie Africaine d\'Aviation', 'E9', NULL, NULL),
(341, 'Air Mali', 'I5', NULL, NULL),
(342, 'Compass Airlines', 'CP', NULL, NULL),
(343, 'Condor Flugdienst', 'DE', NULL, NULL),
(344, 'Contact Air', 'C3', NULL, NULL),
(345, 'Continental Airlines', 'CO', NULL, NULL),
(346, 'Continental Airways', 'PC', NULL, NULL),
(347, 'Continental Micronesia', 'CS', NULL, NULL),
(348, 'Conviasa', 'V0', NULL, NULL),
(349, 'Copa Airlines', 'CM', NULL, NULL),
(350, 'Corporate Express', '2', NULL, NULL),
(351, 'Corsairfly', 'SS', NULL, NULL),
(352, 'Cosmic Air', 'F5', NULL, NULL),
(353, 'Coyne Aviation', '7C', NULL, NULL),
(354, 'Croatia Airlines', 'OU', NULL, NULL),
(355, 'Cubana de Aviacion', 'CU', NULL, NULL),
(356, 'Custom Air Transport', '5R', NULL, NULL),
(357, 'Cyprus Airways', 'CY', NULL, NULL),
(358, 'Cyprus Turkish Airlines (KTHY Kibris Turk Hava Yollari)', 'KY', NULL, NULL),
(359, 'Czech Airlines', 'OK', NULL, NULL),
(360, 'DAT Danish Air Transport', 'DX', NULL, NULL),
(361, 'DHL Aero Expreso', 'D5', NULL, NULL),
(362, 'DHL Air UK', 'D0', NULL, NULL),
(363, 'DHL International Aviation ME', 'ES', NULL, NULL),
(364, 'DHL de Guatemala', 'L3', NULL, NULL),
(365, 'DOT LT', 'R6', NULL, NULL),
(366, 'DRF Luftrettung', '1I', NULL, NULL),
(367, 'Daallo Airlines', 'D3', NULL, NULL),
(368, 'Dagestan Airlines', 'N2', NULL, NULL),
(369, 'Darwin Airline', '0D', NULL, NULL),
(370, 'Deer Jet', 'JD', NULL, NULL),
(371, 'Delta Air Lines', 'DL', NULL, NULL),
(372, 'Denim Air', '3D', NULL, NULL),
(373, 'Direktflyg', 'HS', NULL, NULL),
(374, 'Dirgantara Air Service', 'AW', NULL, NULL),
(375, 'Djibouti Airlines', 'D8', NULL, NULL),
(376, 'Dniproavia', 'Z6', NULL, NULL),
(377, 'Dolphin Air', 'ZD', NULL, NULL),
(378, 'DonbassAero', '5D', NULL, NULL),
(379, 'Dragonair, Hong Kong Dragon Airlines', 'KA', NULL, NULL),
(380, 'Druk Air', 'KB', NULL, NULL),
(381, 'Dutch Antilles Express', '9H', NULL, NULL),
(382, 'EVA Air', 'BR', NULL, NULL),
(383, 'Eagle Air', 'H7', NULL, NULL),
(384, 'Eagle Airways', 'NZ', NULL, NULL),
(385, 'East African', 'QU', NULL, NULL),
(386, 'East African Safari Air Express', 'S9', NULL, NULL),
(387, 'East Star Air', '8C', NULL, NULL),
(388, 'Eastern Airways', 'T3', NULL, NULL),
(389, 'Eastern Australia Airlines', 'QF', NULL, NULL),
(390, 'EasyFly', 'EF', NULL, NULL),
(391, 'Ecuato Guineana', '8Y', NULL, NULL),
(392, 'Edelweiss Air', 'WK', NULL, NULL),
(393, 'EgyptAir Cargo', 'MS', NULL, NULL),
(394, 'EgyptAir Express', 'MS', NULL, NULL),
(395, 'Egyptair', 'MS', NULL, NULL),
(396, 'El Al Israel Airlines', 'LY', NULL, NULL),
(397, 'Emirates Airline', 'EK', NULL, NULL),
(398, 'Empire Airlines', 'EM', NULL, NULL),
(399, 'Empresa Ecuatoriana De Aviacion', 'EU', NULL, NULL),
(400, 'Enkor', 'G8', NULL, NULL),
(401, 'Era Aviation', '7H', NULL, NULL),
(402, 'Eritrean Airlines', 'B8', NULL, NULL),
(403, 'Estafeta Carga Aerea', 'E7', NULL, NULL),
(404, 'Estonian Air', 'OV', NULL, NULL),
(405, 'Ethiopian Airlines', 'ET', NULL, NULL),
(406, 'Etihad Airways', 'EY', NULL, NULL),
(407, 'Euro-Asia Air', '5B', NULL, NULL),
(408, 'EuroAir', '6M', NULL, NULL),
(409, 'Eurocypria Airlines', 'UI', NULL, NULL),
(410, 'Eurofly', 'GJ', NULL, NULL),
(411, 'Eurolot', 'K2', NULL, NULL),
(412, 'Europe Airpost', '5O', NULL, NULL),
(413, 'European Air Transport', 'QY', NULL, NULL),
(414, 'Eurowings', 'EW', NULL, NULL),
(415, 'Evergreen International Airlines', 'EZ', NULL, NULL),
(416, 'Everts Air Cargo', '3Z', NULL, NULL),
(417, 'Executive Airlines', 'OW', NULL, NULL),
(418, 'Expo Aviation', '8D', NULL, NULL),
(419, 'Express One International', 'EO', NULL, NULL),
(420, 'ExpressJet Airlines', 'XE', NULL, NULL),
(421, 'Eznis Airways', 'ZY', NULL, NULL),
(422, 'FS Air Service', '4A', NULL, NULL),
(423, 'Faso Airways', 'F3', NULL, NULL),
(424, 'FedEx Express', 'FX', NULL, NULL),
(425, 'Finnair', 'AY', NULL, NULL),
(426, 'Finncomm Airlines', 'FC', NULL, NULL),
(427, 'Firefly', 'FY', NULL, NULL),
(428, 'First Air', '7F', NULL, NULL),
(429, 'Flex Linhas Aéreas', 'JH', NULL, NULL),
(430, 'Flight Alaska', '4Y', NULL, NULL),
(431, 'Florida West International Airways', 'RF', NULL, NULL),
(432, 'Fly Wex', '6P', NULL, NULL),
(433, 'Fly540', '5H', NULL, NULL),
(434, 'FlyLal (Lithuanian Airlines)', 'TE', NULL, NULL),
(435, 'Flybaboo', 'F7', NULL, NULL),
(436, 'Flybe', 'BE', NULL, NULL),
(437, 'Flyglobespan', 'B4', NULL, NULL),
(438, 'Flying Carpet', '7Y', NULL, NULL),
(439, 'Four Star Aviation / Four Star Cargo', 'HK', NULL, NULL),
(440, 'Freebird Airlines', 'XD', NULL, NULL),
(441, 'Freedom Air', 'FP', NULL, NULL),
(442, 'Freedom Airlines', 'F8', NULL, NULL),
(443, 'Frontier Airlines', 'F9', NULL, NULL),
(444, 'Frontier Flying Service', '2F', NULL, NULL),
(445, 'Gabon Airlines', 'GY', NULL, NULL),
(446, 'Gadair European Airlines', 'GP', NULL, NULL),
(447, 'Galaxy Air', '7O', NULL, NULL),
(448, 'Garuda Indonesia', 'GA', NULL, NULL),
(449, 'Gazpromavia', '4G', NULL, NULL),
(450, 'Georgian Airways', 'A9', NULL, NULL),
(451, 'Georgian National Airlines', 'QB', NULL, NULL),
(452, 'Germania', 'ST', NULL, NULL),
(453, 'Germanwings', '4U', NULL, NULL),
(454, 'Gestair', 'GP', NULL, NULL),
(455, 'Ghana International Airlines', 'G0', NULL, NULL),
(456, 'Global Supply Systems', 'XH', NULL, NULL),
(457, 'GoAir', 'G8', NULL, NULL),
(458, 'GoJet Airlines', 'G7', NULL, NULL),
(459, 'Gol Transportes Aéreos', 'G3', NULL, NULL),
(460, 'Golden Air', 'DC', NULL, NULL),
(461, 'Gomelavia', 'YD', NULL, NULL),
(462, 'Gorkha Airlines', 'G1', NULL, NULL),
(463, 'Grand Canyon Airlines', 'YR', NULL, NULL),
(464, 'Grand China Express Air', 'GS', NULL, NULL),
(465, 'Grant Aviation', 'GS', NULL, NULL),
(466, 'Great Lakes Airlines', 'ZK', NULL, NULL),
(467, 'Great Wall Airlines', 'IJ', NULL, NULL),
(468, 'Guine Bissaur Airlines', 'G6', NULL, NULL),
(469, 'Guinee Airlines', 'J9', NULL, NULL),
(470, 'Gulf Air Bahrain', 'GF', NULL, NULL),
(471, 'Gulfstream International Airlines', '3M', NULL, NULL),
(472, 'Hageland Aviation Services', 'H6', NULL, NULL),
(473, 'Hahn Air', 'HR', NULL, NULL),
(474, 'Hainan Airlines', 'HU', NULL, NULL),
(475, 'Hamburg International', '4R', NULL, NULL),
(476, 'Hawaiian Airlines', 'HA', NULL, NULL),
(477, 'Heavylift Cargo Airlines', 'HN', NULL, NULL),
(478, 'Heli Air Monaco', 'YO', NULL, NULL),
(479, 'Helijet', 'JB', NULL, NULL),
(480, 'Hellas Jet', 'T4', NULL, NULL),
(481, 'Hellenic Imperial Airways', 'HT', NULL, NULL),
(482, 'Hello', 'HW', NULL, NULL),
(483, 'Helvetic Airways', '2L', NULL, NULL),
(484, 'Hemus Air', 'DU', NULL, NULL),
(485, 'Hewa Bora Airways', 'EO', NULL, NULL),
(486, 'Hex\'Air', 'UD', NULL, NULL),
(487, 'Hi Fly', '5K', NULL, NULL),
(488, 'Highland Airways', '8H', NULL, NULL),
(489, 'Hokkaido International Airlines', 'HD', NULL, NULL),
(490, 'Hola Airlines', 'H5', NULL, NULL),
(491, 'Hong Kong Airlines', 'N8', NULL, NULL),
(492, 'Hong Kong Express Airways', 'UO', NULL, NULL),
(493, 'Horizon Air', 'QX', NULL, NULL),
(494, 'IBC Airways', 'II', NULL, NULL),
(495, 'Iberia Airlines', 'IB', NULL, NULL),
(496, 'Iberworld', 'TY', NULL, NULL),
(497, 'Ibex Airlines', 'FW', NULL, NULL),
(498, 'Icaro Air', 'X8', NULL, NULL),
(499, 'Icelandair', 'FI', NULL, NULL),
(500, 'Imair Airlines', 'IK', NULL, NULL),
(501, 'IndiGo Airlines', '6E', NULL, NULL),
(502, 'Indonesia Air Transport', 'I8', NULL, NULL),
(503, 'Indonesia AirAsia', 'QZ', NULL, NULL),
(504, 'Insel Air', '7I', NULL, NULL),
(505, 'InterSky', '3L', NULL, NULL),
(506, 'Interair South Africa', 'D6', NULL, NULL),
(507, 'Interjet', '4O', NULL, NULL),
(508, 'Interlink Airlines', 'ID', NULL, NULL),
(509, 'International Business Air', '6I', NULL, NULL),
(510, 'Interstate Airline', 'I4', NULL, NULL),
(511, 'Iran Air', 'IR', NULL, NULL),
(512, 'Iran Air Tours', 'B9', NULL, NULL),
(513, 'Iran Aseman Airlines', 'EP', NULL, NULL),
(514, 'Iraqi Airways', 'IA', NULL, NULL),
(515, 'Island Air', 'WP', NULL, NULL),
(516, 'Island Express', '2S', NULL, NULL),
(517, 'Islas Airways', 'IF', NULL, NULL),
(518, 'Islena De Inversiones', 'WC', NULL, NULL),
(519, 'Isles of Scilly Skybus', '5Y', NULL, NULL),
(520, 'Israir Airlines', '6H', NULL, NULL),
(521, 'ItAli Airlines', '9X', NULL, NULL),
(522, 'Itek Air', 'GI', NULL, NULL),
(523, 'Izair', 'H9', NULL, NULL),
(524, 'J-Air', 'XM', NULL, NULL),
(525, 'JAL Express', 'JC', NULL, NULL),
(526, 'JALways', 'JO', NULL, NULL),
(527, 'Jade Cargo International', 'JI', NULL, NULL),
(528, 'Japan Air Commuter', '3X', NULL, NULL),
(529, 'Japan Airlines', 'JL', NULL, NULL),
(530, 'Japan Transocean Air', 'NU', NULL, NULL),
(531, 'Jat Airways', 'JU', NULL, NULL),
(532, 'Jazeera Airways', 'J9', NULL, NULL),
(533, 'Jeju Air', '7C', NULL, NULL),
(534, 'Jet Air', 'O2', NULL, NULL),
(535, 'Jet Airways', '9W', NULL, NULL),
(536, 'Jet Aviation', 'PP', NULL, NULL),
(537, 'Jet2.com', 'LS', NULL, NULL),
(538, 'Jet4you', '8J', NULL, NULL),
(539, 'JetBlue Airways', 'B6', NULL, NULL),
(540, 'JetConnect', 'QF', NULL, NULL),
(541, 'JetLite', 'S2', NULL, NULL),
(542, 'Jetairfly', 'JF', NULL, NULL),
(543, 'Jetclub', '0J', NULL, NULL),
(544, 'Jetstar Airways', 'JQ', NULL, NULL),
(545, 'Jetstar Asia Airways', '3K', NULL, NULL),
(546, 'Jetstar Pacific', 'BL', NULL, NULL),
(547, 'Jett8 Airlines Cargo', 'JX', NULL, NULL),
(548, 'Jin Air', 'LJ', NULL, NULL),
(549, 'Jordan Aviation', 'R5', NULL, NULL),
(550, 'Jubba Airways', '6J', NULL, NULL),
(551, 'Juneyao Airlines', 'HO', NULL, NULL),
(552, 'KD Air', 'XC', NULL, NULL),
(553, 'KD Avia', 'KD', NULL, NULL),
(554, 'KLM Cityhopper', 'WA', NULL, NULL),
(555, 'KLM Royal Dutch Airlines', 'KL', NULL, NULL),
(556, 'Kabo Air', 'N2', NULL, NULL),
(557, 'Kalitta Air', 'K4', NULL, NULL),
(558, 'Kalitta Charters', 'K9', NULL, NULL),
(559, 'Kam Air', 'RQ', NULL, NULL),
(560, 'Kampuchea Airlines', 'E2', NULL, NULL),
(561, 'Karthago Airlines', '5R', NULL, NULL),
(562, 'Kartika Airlines', '3Y', NULL, NULL),
(563, 'Kavminvodyavia', 'KV', NULL, NULL),
(564, 'Kelowna Flightcraft Air Charter', 'KW', NULL, NULL),
(565, 'Kenmore Air', 'M5', NULL, NULL),
(566, 'Kenn Borek Air', '4K', NULL, NULL),
(567, 'Kenya Airways', 'KQ', NULL, NULL),
(568, 'Keystone Air Services', 'BZ', NULL, NULL),
(569, 'Khors Aircompany', 'X9', NULL, NULL),
(570, 'Kingfisher Airlines', 'IT', NULL, NULL),
(571, 'Kingfisher Red', 'DN', NULL, NULL),
(572, 'Kish Air', 'Y9', NULL, NULL),
(573, 'Kogalymavia', '7K', NULL, NULL),
(574, 'KoralBlue Airlines', 'K7', NULL, NULL),
(575, 'Korean Air', 'KE', NULL, NULL),
(576, 'Kuban Airlines', 'GW', NULL, NULL),
(577, 'Kunpeng Airlines', 'VD', NULL, NULL),
(578, 'Kuwait Airways', 'KU', NULL, NULL),
(579, 'Kuzu Airlines Cargo', 'GO', NULL, NULL),
(580, 'Kyrgyzstan', 'QH', NULL, NULL),
(581, 'Kyrgyzstan Airlines', 'R8', NULL, NULL),
(582, 'L\'Avion', 'A0', NULL, NULL),
(583, 'L.A.B. Flying Service', 'JF', NULL, NULL),
(584, 'LACSA', 'LR', NULL, NULL),
(585, 'LADE - Líneas Aéreas del Estado', '5U', NULL, NULL),
(586, 'LAI - Linea Aerea IAACA', 'KG', NULL, NULL),
(587, 'LAM Mozambique Airlines', 'LM', NULL, NULL),
(588, 'LAN Airlines', 'LA', NULL, NULL),
(589, 'LAN Argentina', '4M', NULL, NULL),
(590, 'LAN Cargo', 'UC', NULL, NULL),
(591, 'LAN Ecuador', 'XL', NULL, NULL),
(592, 'LAN Express', 'LU', NULL, NULL),
(593, 'LAN Peru', 'LP', NULL, NULL),
(594, 'LASER Airlines', '8z', NULL, NULL),
(595, 'LOT Polish Airlines', 'LO', NULL, NULL),
(596, 'LTU International', 'LT', NULL, NULL),
(597, 'Lankair', 'IK', NULL, NULL),
(598, 'Lao Airlines', 'QV', NULL, NULL),
(599, 'Lauda Air', 'NG', NULL, NULL),
(600, 'Leeward Islands Air Transport', 'LI', NULL, NULL),
(601, 'Libyan Airlines', 'LN', NULL, NULL),
(602, 'Lignes Aériennes Congolaises', '4V', NULL, NULL),
(603, 'Linea Turistica Aerotuy', 'LD', NULL, NULL),
(604, 'Lion Air (Lion Mentari Airlines )', 'JT', NULL, NULL),
(605, 'Livingston Energy Flight', 'LM', NULL, NULL),
(606, 'Loganair', 'LC', NULL, NULL),
(607, 'Lotus Air', 'T2', NULL, NULL),
(608, 'Lucky Air', '8L', NULL, NULL),
(609, 'Luftfahrtgesellschaft Walter', 'HE', NULL, NULL),
(610, 'Lufthansa', 'LH', NULL, NULL),
(611, 'Lufthansa Cargo', 'LH', NULL, NULL),
(612, 'Lufthansa CityLine', 'CL', NULL, NULL),
(613, 'Lufttaxi Fluggesellschaft', 'DV', NULL, NULL),
(614, 'Lufttransport', 'L5', NULL, NULL),
(615, 'Luxair', 'LG', NULL, NULL),
(616, 'Lviv Airlines', '5V', NULL, NULL),
(617, 'Lynden Air Cargo', 'L2', NULL, NULL),
(618, 'Lynx Aviation', 'L4', NULL, NULL),
(619, 'MASkargo (Malaysia Airlines Kargo)', 'MH', NULL, NULL),
(620, 'MASwings', 'MH', NULL, NULL),
(621, 'MAT Macedonian Airlines', 'IN', NULL, NULL),
(622, 'MIAT Mongolian Airlines', 'OM', NULL, NULL),
(623, 'MK Airlines', '7G', NULL, NULL),
(624, 'MNG Airlines', 'MB', NULL, NULL),
(625, 'Macair Airlines', 'CC', NULL, NULL),
(626, 'Magnicharters', 'UJ', NULL, NULL),
(627, 'Mahan Air', 'W5', NULL, NULL),
(628, 'Malaysia Airlines', 'MH', NULL, NULL),
(629, 'Maldivian', 'Q2', NULL, NULL),
(630, 'Maldivian Air Taxi', 'MV', NULL, NULL),
(631, 'Malev Hungarian Airlines', 'MA', NULL, NULL),
(632, 'Mali Airways', 'Z8', NULL, NULL),
(633, 'Braathens Regional Aviation', 'TF', NULL, NULL),
(634, 'Mandala Airlines', 'RI', NULL, NULL),
(635, 'Mandarin Airlines', 'AE', NULL, NULL),
(636, 'Mango', 'JE', NULL, NULL),
(637, 'Mars RK', '6V', NULL, NULL),
(638, 'Marsland Aviation', 'M7', NULL, NULL),
(639, 'Martinair', 'MP', NULL, NULL),
(640, 'MasAir', 'M7', NULL, NULL),
(641, 'Mauritania Airlines International', 'L6', NULL, NULL),
(642, 'Maxair', '8M', NULL, NULL),
(643, 'Maya Island Air', 'MW', NULL, NULL),
(644, 'Medavia', 'N5', NULL, NULL),
(645, 'Menajet', 'IM', NULL, NULL),
(646, 'Meridiana', 'IG', NULL, NULL),
(647, 'Merpati Nusantara Airlines', 'MZ', NULL, NULL),
(648, 'Mesa Airlines', 'YV', NULL, NULL),
(649, 'Mesaba Airlines', 'XJ', NULL, NULL),
(650, 'Mexicana', 'MX', NULL, NULL),
(651, 'MexicanaClick', 'QA', NULL, NULL),
(652, 'Miami Air International', 'GL', NULL, NULL),
(653, 'Mid Airlines', '7Y', NULL, NULL),
(654, 'Middle East Airlines', 'ME', NULL, NULL),
(655, 'Midway Airlines', 'JI', NULL, NULL),
(656, 'Midwest Airlines', 'MY', NULL, NULL),
(657, 'Mihin Lanka', 'MJ', NULL, NULL),
(658, 'Mokulele Airlines', 'MW', NULL, NULL),
(659, 'Moldavian Airlines', '2M', NULL, NULL),
(660, 'Monarch Airlines', 'ZB', NULL, NULL),
(661, 'Montenegro Airlines', 'YM', NULL, NULL),
(662, 'Moskovia Airlines', '3R', NULL, NULL),
(663, 'Motor Sich', 'M9', NULL, NULL),
(664, 'Mount Cook Airlines', 'NM', NULL, NULL),
(665, 'MyAir', '8I', NULL, NULL),
(666, 'Myanma Airways', 'UB', NULL, NULL),
(667, 'Myanmar Airways International', '8M', NULL, NULL),
(668, 'Nantucket Airlines', 'DV', NULL, NULL),
(669, 'Nas Air', 'XY', NULL, NULL),
(670, 'Nasair', 'UE', NULL, NULL),
(671, 'National Airlines', '5M', NULL, NULL),
(672, 'National Airways', 'YJ', NULL, NULL),
(673, 'National Jet Systems', 'NC', NULL, NULL),
(674, 'Nature Air', '5C', NULL, NULL),
(675, 'Nauru Air Corporation', 'ON', NULL, NULL),
(676, 'Navegacion y Servicios Aéreos Canarios', 'ZN', NULL, NULL),
(677, 'Neos', 'NO', NULL, NULL),
(678, 'Nepal Airlines', 'RA', NULL, NULL),
(679, 'NetJets', '1I', NULL, NULL),
(680, 'NetJets Europe', '1I', NULL, NULL),
(681, 'New England Airlines', 'EJ', NULL, NULL),
(682, 'Nextjet', '2N', NULL, NULL),
(683, 'Niki', 'HG', NULL, NULL),
(684, 'Nippon Cargo Airlines', 'KZ', NULL, NULL),
(685, 'Nok Air', 'DD', NULL, NULL),
(686, 'Nordic Airways', '6N', NULL, NULL),
(687, 'Nordic Regional', '6N', NULL, NULL),
(688, 'North American Airlines', 'NA', NULL, NULL),
(689, 'North Flying', 'M3', NULL, NULL),
(690, 'North-Wright Airways', 'HW', NULL, NULL),
(691, 'Northern Air Cargo', 'NC', NULL, NULL),
(692, 'Northwest Airlines', 'NW', NULL, NULL),
(693, 'Northwest Regional Airlines', 'FY', NULL, NULL),
(694, 'Northwestern Air', 'J3', NULL, NULL),
(695, 'Norwegian Air Shuttle', 'DY', NULL, NULL),
(696, 'Nouvelair', 'BJ', NULL, NULL),
(697, 'Nova Airline', 'M4', NULL, NULL),
(698, 'Novair', '1I', NULL, NULL),
(699, 'OLT - Ostfriesische Lufttransport', 'OL', NULL, NULL),
(700, 'Oceanair', 'O6', NULL, NULL),
(701, 'Odessa Airlines', '5K', NULL, NULL),
(702, 'Okay Airways', 'BK', NULL, NULL),
(703, 'Olympic Airlines', 'OA', NULL, NULL),
(704, 'Oman Air', 'WY', NULL, NULL),
(705, 'Omni Air International', 'OY', NULL, NULL),
(706, 'One-Two-GO Airlines', 'OX', NULL, NULL),
(707, 'Onur Air', '8Q', NULL, NULL),
(708, 'OpenSkies', 'EC', NULL, NULL),
(709, 'Orenair (Orenburg Airlines)', 'R2', NULL, NULL),
(710, 'Orient Thai Airlines', 'OX', NULL, NULL),
(711, 'Overland Airways', 'OJ', NULL, NULL),
(712, 'Ozjet Airlines', 'O7', NULL, NULL),
(713, 'PAN Air', 'PV', NULL, NULL),
(714, 'PB Air', '9Q', NULL, NULL),
(715, 'PLUNA', 'PU', NULL, NULL),
(716, 'PMTair', 'U4', NULL, NULL),
(717, 'PSA Airlines', 'US', NULL, NULL),
(718, 'Pace Airlines', 'Y5', NULL, NULL),
(719, 'Pacific Blue Airlines', 'DJ', NULL, NULL),
(720, 'Pacific Coastal Airline', '8P', NULL, NULL),
(721, 'Pacific East Asia Cargo Airlines', 'Q8', NULL, NULL),
(722, 'Pacific Wings', 'LW', NULL, NULL),
(723, 'Pakistan International Airlines', 'PK', NULL, NULL),
(724, 'Palestinian Airlines', 'PF', NULL, NULL),
(725, 'Pamir Airways', 'NR', NULL, NULL),
(726, 'Panafrican Airways', 'PQ', NULL, NULL),
(727, 'Pantanal Linhas Aereas Sul-Matogrossenses', 'P8', NULL, NULL),
(728, 'Paramount Airways', 'I7', NULL, NULL),
(729, 'Payam Air', '2F', NULL, NULL),
(730, 'Pearl Airways', 'HP', NULL, NULL),
(731, 'Pegasus Airlines', 'H9', NULL, NULL),
(732, 'Pelican Air Services', '7V', NULL, NULL),
(733, 'Pelita Air Service', '6D', NULL, NULL),
(734, 'PenAir (Peninsula Airways)', 'KS', NULL, NULL),
(735, 'People\'s Viennaline', 'PE', NULL, NULL),
(736, 'Perimeter Aviation (Perimeter Airlines)', '4B', NULL, NULL),
(737, 'Perm Airlines', 'P9', NULL, NULL),
(738, 'Philippine Airlines', 'PR', NULL, NULL),
(739, 'Phuket Air', '9R', NULL, NULL),
(740, 'Piedmont Airlines', 'PI', NULL, NULL),
(741, 'Pinnacle Airlines', '9E', NULL, NULL),
(742, 'Polar Air Cargo', 'PO', NULL, NULL),
(743, 'Polet Airlines', 'YQ', NULL, NULL),
(744, 'Polynesian Airlines', 'PH', NULL, NULL),
(745, 'Porter Airlines', 'PD', NULL, NULL),
(746, 'Portugalia', 'NI', NULL, NULL),
(747, 'Precision Air', 'PW', NULL, NULL),
(748, 'President Airlines', 'TO', NULL, NULL),
(749, 'Primera Air', 'GX', NULL, NULL),
(750, 'Private Wings Flugcharter', '8W', NULL, NULL),
(751, 'Provincial Airlines', 'PB', NULL, NULL),
(752, 'Qantas', 'QF', NULL, NULL),
(753, 'Qatar Airways', 'QR', NULL, NULL),
(754, 'RAK Airways', 'RT', NULL, NULL),
(755, 'Red Wings Airlines', 'WZ', NULL, NULL),
(756, 'Redhill Aviation', '8L', NULL, NULL),
(757, 'Regional Air Lines', 'FN', NULL, NULL),
(758, 'Regional Compagnie Aerienne Europeenne', 'YS', NULL, NULL),
(759, 'Regional Express Airlines', 'ZL', NULL, NULL),
(760, 'Republic Airlines', 'RW', NULL, NULL),
(761, 'Republic Express Airlines', 'RH', NULL, NULL),
(762, 'Riau Airlines', 'PK', NULL, NULL),
(763, 'Rico Linhas Aereas', 'C7', NULL, NULL),
(764, 'Romavia', 'WQ', NULL, NULL),
(765, 'Rossiya - Russian Airlines', 'FV', NULL, NULL),
(766, 'Royal Air Force', 'RR', NULL, NULL),
(767, 'Royal Air Force of Oman', 'RS', NULL, NULL),
(768, 'Royal Air Maroc', 'AT', NULL, NULL),
(769, 'Royal Airlines', 'R0', NULL, NULL),
(770, 'Royal Brunei Airlines', 'BI', NULL, NULL),
(771, 'Royal Daisy Airlines', '6D', NULL, NULL),
(772, 'Royal Jordanian', 'RJ', NULL, NULL),
(773, 'Royal Khmer Airlines', 'RK', NULL, NULL),
(774, 'Royal Phnom Penh Airways', 'RL', NULL, NULL),
(775, 'Russian Sky Airlines', 'P7', NULL, NULL),
(776, 'Rwandair Express', 'WB', NULL, NULL),
(777, 'Ryan International Airlines', 'RD', NULL, NULL),
(778, 'Ryanair', 'FR', NULL, NULL),
(779, 'S7 Airlines (Siberia Airlines)', 'S7', NULL, NULL),
(780, 'SAM Colombia', 'MM', NULL, NULL),
(781, 'SAT Airlines', 'HZ', NULL, NULL),
(782, 'SATA Air Acores', 'SP', NULL, NULL),
(783, 'SATA International', 'S4', NULL, NULL),
(784, 'SATENA', '9N', NULL, NULL),
(785, 'SGA Airlines', '5E', NULL, NULL),
(786, 'Sabah Air', 'SA', NULL, NULL),
(787, 'Safair', 'FA', NULL, NULL),
(788, 'Saint Barth Commuter', 'PV', NULL, NULL),
(789, 'Sama Airlines', 'ZS', NULL, NULL),
(790, 'Santa Barbara Airlines', 'S3', NULL, NULL),
(791, 'Saravia', '6W', NULL, NULL),
(792, 'Sat Airlines', 'HZ', NULL, NULL),
(793, 'Saudi Arabian Airlines', 'SV', NULL, NULL),
(794, 'Sayakhat Airlines', 'W7', NULL, NULL),
(795, 'Scandinavian Airlines System (SAS)', 'SK', NULL, NULL),
(796, 'Scat Aircompany', 'DV', NULL, NULL),
(797, 'Scenic Airlines', 'YR', NULL, NULL),
(798, 'ScotAirways', 'CB', NULL, NULL),
(799, 'Seaborne Airlines', 'BB', NULL, NULL),
(800, 'Seagle Air', 'SJ', NULL, NULL),
(801, 'Servicios Aereos Profesionales', '5S', NULL, NULL),
(802, 'Servicios de Transportes Aereos Fueguinos', 'FS', NULL, NULL),
(803, 'Shaheen Air International', 'NL', NULL, NULL),
(804, 'Shandong Airlines', 'SC', NULL, NULL),
(805, 'Shanghai Airlines', 'FM', NULL, NULL),
(806, 'Shanghai Airlines Cargo', 'F4', NULL, NULL),
(807, 'Shanxi Airlines', '8C', NULL, NULL),
(808, 'Shenzhen Airlines', 'ZH', NULL, NULL),
(809, 'Shenzhen Donghai Airlines', 'J5', NULL, NULL),
(810, 'Shuttle America', 'S5', NULL, NULL),
(811, 'Sichuan Airlines', '3U', NULL, NULL),
(812, 'Sierra National Airlines', 'LJ', NULL, NULL),
(813, 'Sierra Pacific Airlines', 'SI', NULL, NULL),
(814, 'Silk Way Airlines', 'ZP', NULL, NULL),
(815, 'SilkAir', 'MI', NULL, NULL),
(816, 'Singapore Airlines', 'SQ', NULL, NULL),
(817, 'Singapore Airlines Cargo', 'SQ', NULL, NULL),
(818, 'Sky Airline', 'H2', NULL, NULL),
(819, 'Sky Airlines', 'SY', NULL, NULL),
(820, 'Sky Express', 'G3', NULL, NULL),
(821, 'Sky Express', 'XW', NULL, NULL),
(822, 'Sky Eyes', 'I6', NULL, NULL),
(823, 'SkyEurope', 'NE', NULL, NULL),
(824, 'SkyWest Airlines', 'OO', NULL, NULL),
(825, 'Skymark Airlines', 'BC', NULL, NULL),
(826, 'Skynet Asia Airways', '6J', NULL, NULL),
(827, 'Skyservice Airlines', '5G', NULL, NULL),
(828, 'Skytrans Airlines', 'NP', NULL, NULL),
(829, 'Skyway Enterprises', 'KI', NULL, NULL),
(830, 'Skyways Express', 'JZ', NULL, NULL),
(831, 'Skywest Airlines', 'XR', NULL, NULL),
(832, 'Smart Wings', 'QS', NULL, NULL),
(833, 'SmartLynx Airlines', '6Y', NULL, NULL),
(834, 'Sol Dominicana Airlines', 'DA', NULL, NULL),
(835, 'Solomon Airlines', 'IE', NULL, NULL),
(836, 'South African Airways', 'SA', NULL, NULL),
(837, 'South African Express', 'YB', NULL, NULL),
(838, 'South Airlines', 'YG', NULL, NULL),
(839, 'South East Asian Airlines', 'DG', NULL, NULL),
(840, 'Southern Air', '9S', NULL, NULL),
(841, 'Southern Air Charter', 'PL', NULL, NULL),
(842, 'Southwest Airlines', 'WN', NULL, NULL),
(843, 'Spanair', 'JK', NULL, NULL),
(844, 'Spicejet', 'SG', NULL, NULL),
(845, 'Spirit Airlines', 'NK', NULL, NULL),
(846, 'Spring Airlines', '9S', NULL, NULL),
(847, 'SriLankan Airlines', 'UL', NULL, NULL),
(848, 'Sriwijaya Air', 'SJ', NULL, NULL),
(849, 'Star Air', 'S6', NULL, NULL),
(850, 'Star Air Aviation', '6S', NULL, NULL),
(851, 'Star Flyer', '7G', NULL, NULL),
(852, 'Star Perú', '2I', NULL, NULL),
(853, 'Starline.kz', 'DZ', NULL, NULL),
(854, 'Sudan Airways', 'SD', NULL, NULL),
(855, 'Sun Air of Scandinavia', 'EZ', NULL, NULL),
(856, 'Sun Country Airlines', 'SY', NULL, NULL),
(857, 'Sun d\'Or International Airlines', '7L', NULL, NULL),
(858, 'SunExpress', 'XQ', NULL, NULL),
(859, 'Sunshine Express Airlines', 'CQ', NULL, NULL),
(860, 'Sunstate Airlines', 'QF', NULL, NULL),
(861, 'Sunwing Airlines', 'WG', NULL, NULL),
(862, 'Superior Aviation', 'SO', NULL, NULL),
(863, 'Surinam Airways', 'PY', NULL, NULL),
(864, 'Swaziland Airlink', 'SA', NULL, NULL),
(865, 'Swift Air', 'Q7', NULL, NULL),
(866, 'Swiftair', 'W3', NULL, NULL),
(867, 'Swiss European Air Lines', 'LX', NULL, NULL),
(868, 'Swiss International Air Lines', 'LX', NULL, NULL),
(869, 'Sylt Air', '7E', NULL, NULL),
(870, 'Syrian Arab Airlines (Syrianair)', 'RB', NULL, NULL),
(871, 'TAAG Angola Airlines (Linhas Aéreas de Angola)', 'DT', NULL, NULL),
(872, 'TACA Peru', 'T0', NULL, NULL),
(873, 'TACV', 'VR', NULL, NULL),
(874, 'TACV Cabo Verde Airlines', 'VR', NULL, NULL),
(875, 'TAF Linhas Aéreas', 'R9', NULL, NULL),
(876, 'TAM Airlines', 'PZ', NULL, NULL),
(877, 'TAM Airlines (TAM Linhas Aereas)', 'JJ', NULL, NULL),
(878, 'TAME', 'EQ', NULL, NULL),
(879, 'TAP Portugal', 'TP', NULL, NULL),
(880, 'TNT Airways', '3V', NULL, NULL),
(881, 'TRIP Linhas Aereas', '8R', NULL, NULL),
(882, 'TUIfly', 'X3', NULL, NULL),
(883, 'TUIfly Nordic', '6B', NULL, NULL),
(884, 'Tajik Air', '7J', NULL, NULL),
(885, 'Tampa Cargo', 'QT', NULL, NULL),
(886, 'Tandem Aero', 'TQ', NULL, NULL),
(887, 'Tarom', 'RO', NULL, NULL),
(888, 'Tassili Airlines', 'SF', NULL, NULL),
(889, 'Tatarstan Airlines', 'U9', NULL, NULL),
(890, 'Tavrey Airlines', 'T6', NULL, NULL),
(891, 'Tbilaviamsheni', 'L6', NULL, NULL),
(892, 'Thai AirAsia', 'FD', NULL, NULL),
(893, 'Thai Airways International', 'TG', NULL, NULL),
(894, 'Thomas Cook Airlines', 'MT', NULL, NULL),
(895, 'Thomas Cook Airlines', 'FQ', NULL, NULL),
(896, 'Thomas Cook Airlines Scandinavia', 'DK', NULL, NULL),
(897, 'Thomson Airways', 'BY', NULL, NULL),
(898, 'Tiara Air', '3P', NULL, NULL),
(899, 'Tiger Airways', 'TR', NULL, NULL),
(900, 'Tiger Airways Australia', 'TT', NULL, NULL),
(901, 'Titan Airways', 'ZT', NULL, NULL),
(902, 'Tobruk Air', '7T', NULL, NULL),
(903, 'Toumaï Air Tchad', '9D', NULL, NULL),
(904, 'Tradewinds Airlines', 'WI', NULL, NULL),
(905, 'Trans Air Benin', 'N4', NULL, NULL),
(906, 'Trans Air Congo', 'Q8', NULL, NULL),
(907, 'Trans Maldivian Airways', 'M8', NULL, NULL),
(908, 'Trans Mediterranean Airlines', 'TL', NULL, NULL),
(909, 'Trans States Airlines', 'AX', NULL, NULL),
(910, 'TransAVIAexport Airlines', 'AL', NULL, NULL),
(911, 'TransAsia Airways', 'GE', NULL, NULL),
(912, 'Transaero Airlines', 'UN', NULL, NULL),
(913, 'Transcarga', 'T9', NULL, NULL),
(914, 'Transmile Air Services', 'TH', NULL, NULL),
(915, 'Transwede Airways', '5T', NULL, NULL),
(916, 'Transwest Air', '9T', NULL, NULL),
(917, 'Tri-MG Intra Asia Airlines', 'GY', NULL, NULL),
(918, 'Trigana Air Service', 'TN', NULL, NULL),
(919, 'Triple Alpha Luftfahrtgesellschaft', '3A', NULL, NULL),
(920, 'Tropic Air', 'PM', NULL, NULL),
(921, 'Tulpar Air Service', '2T', NULL, NULL),
(922, 'TunisAir Express', 'UG', NULL, NULL),
(923, 'Tunisair', 'TU', NULL, NULL),
(924, 'Turan Air', '3T', NULL, NULL),
(925, 'Turkish Airlines', 'TK', NULL, NULL),
(926, 'Turkmenistan Airlines', 'T5', NULL, NULL),
(927, 'Twin Jet', 'T7', NULL, NULL),
(928, 'UM Airlines', 'UF', NULL, NULL),
(929, 'US Airways', 'US', NULL, NULL),
(930, 'US Helicopter', 'UH', NULL, NULL),
(931, 'USA 3000 Airlines', 'U5', NULL, NULL),
(932, 'USA Jet Airlines', 'UJ', NULL, NULL),
(933, 'UTair Aviation', 'UT', NULL, NULL),
(934, 'Ukraine International Airlines', 'PS', NULL, NULL),
(935, 'Ukrainian Cargo Airways', '6Z', NULL, NULL),
(936, 'Uni Air', 'B7', NULL, NULL),
(937, 'United Airlines', 'UA', NULL, NULL),
(938, 'United Airways (Bangladesh)', '4H', NULL, NULL),
(939, 'United Eagle Airlines', 'EU', NULL, NULL),
(940, 'United Parcel Service', '5X', NULL, NULL),
(941, 'Ural Airlines', 'U6', NULL, NULL),
(942, 'Uzbekistan Airways', 'HY', NULL, NULL),
(943, 'VIM Airlines', 'NN', NULL, NULL),
(944, 'VIP Ecuador', 'V6', NULL, NULL),
(945, 'VLM Airlines', 'VG', NULL, NULL),
(946, 'VRG Linhas Aereas (VARIG)', 'RG', NULL, NULL),
(947, 'Varig Logistica (VarigLog)', 'LC', NULL, NULL),
(948, 'Venezolana', 'RV', NULL, NULL),
(949, 'Viaggio Air', 'VM', NULL, NULL),
(950, 'Vieques Air Link', 'VI', NULL, NULL),
(951, 'Vietnam Airlines', 'VN', NULL, NULL),
(952, 'Viking Airlines', '4P', NULL, NULL),
(953, 'Vintage Props and Jets', 'VQ', NULL, NULL),
(954, 'Virgin America', 'VX', NULL, NULL),
(955, 'Virgin Atlantic Airways', 'VS', NULL, NULL),
(956, 'Virgin Blue', 'DJ', NULL, NULL),
(957, 'Virgin Nigeria Airways', 'VK', NULL, NULL),
(958, 'Viva Macau', 'ZG', NULL, NULL),
(959, 'VivaAerobus', 'VB', NULL, NULL),
(960, 'Vladivostok Air', 'XF', NULL, NULL),
(961, 'Volare Airlines', 'VA', NULL, NULL),
(962, 'Volga-Dnepr Airlines', 'VI', NULL, NULL),
(963, 'Voyageur Airways', 'VC', NULL, NULL),
(964, 'Vueling Airlines', 'VY', NULL, NULL),
(965, 'WDL Aviation', 'W1', NULL, NULL),
(966, 'WaltAir', 'XW', NULL, NULL),
(967, 'Wan Air', '3W', NULL, NULL),
(968, 'Wasaya Airways', 'WT', NULL, NULL),
(969, 'WebJet Linhas Aéreas', 'WJ', NULL, NULL),
(970, 'Welcome Air', '2W', NULL, NULL),
(971, 'West Air Sweden', 'PT', NULL, NULL),
(972, 'WestJet', 'WS', NULL, NULL),
(973, 'Wideroe', 'WF', NULL, NULL),
(974, 'Wiggins Airways', 'WG', NULL, NULL),
(975, 'Wimbi Dira Airways', '9C', NULL, NULL),
(976, 'Wind Jet', 'IV', NULL, NULL),
(977, 'Wind Rose Aviation', '7W', NULL, NULL),
(978, 'Windward Islands Airways', 'WM', NULL, NULL),
(979, 'Wings Air', '1W', NULL, NULL),
(980, 'Wings of Alaska', 'K5', NULL, NULL),
(981, 'Wizz Air', 'W6', NULL, NULL),
(982, 'Wizz Air', 'W6', NULL, NULL),
(983, 'World Airways', 'WO', NULL, NULL),
(984, 'Wright Air Service', '8V', NULL, NULL),
(985, 'XL Airways France', 'SE', NULL, NULL),
(986, 'XL Airways Germany', '9E', NULL, NULL),
(987, 'Xiamen Airlines', 'MF', NULL, NULL),
(988, 'Xtra Airways', 'XP', NULL, NULL),
(989, 'Yakutia Airlines', 'R3', NULL, NULL),
(990, 'Yamal Airlines', 'YL', NULL, NULL),
(991, 'Yangtze River Express', 'Y8', NULL, NULL),
(992, 'Yemenia - Yemen Airways', 'IY', NULL, NULL),
(993, 'Yeongnam Air', 'OE', NULL, NULL),
(994, 'Yuzmashavia', '2N', NULL, NULL),
(995, 'Zambia Skyways', 'K8', NULL, NULL),
(996, 'Zambian Airways', 'Q3', NULL, NULL),
(997, 'Zest Airways', '6K', NULL, NULL),
(998, 'Zimex Aviation', 'C4', NULL, NULL),
(1089, 'Cobalt Air', 'CO', NULL, NULL),
(1090, 'Blue Air', '0B', NULL, NULL),
(1091, 'Transavia', 'HV', NULL, NULL),
(1092, 'Air Serbia', 'JU', NULL, NULL),
(1093, 'easyJet', 'U2', NULL, NULL),
(1094, 'Gulf Air', 'GF', NULL, NULL),
(1095, 'Norwegian Air International', 'D8', NULL, NULL),
(1096, 'easyJet', 'U2', NULL, NULL),
(1097, 'Globus Airlines', 'GH', NULL, NULL);